project:
  type: website

website:
  title: "Emmanuel Ugochukwu"
  site-url: https://emmanuel-ugo.netlify.app/
  description: "This is Emmanuel Ugochukwu's personal Blog."
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://github.com/EmmanuelUgo
      - icon: twitter
        href: https://https://twitter.com/emm_aguila
      - icon: youtube
        href: https://www.youtube.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/emmanuel-u-6a5971108/
      - icon: rss
        href: blog.xml
  cookie-consent: true
  twitter-card: 
    image: thumbnail_blog.png
    card-style: summary_large_image
    creator: "@emm_aguila"

format:
  html:
    theme: 
      light: theme.scss
      dark: theme-dark.scss

editor: visual

